name = "ttjl"
uuid = "1989a96c-dc04-4193-9e71-0cf1c6a9afa0"
authors = ["Tretyak0ID"]
version = "1.0.0-DEV"

[compat]
julia = "1.9.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
